# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 30, 320, 240))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 270, 323, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dialog1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.dialog1.setObjectName("dialog1")
        self.horizontalLayout.addWidget(self.dialog1)
        self.dialog2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.dialog2.setObjectName("dialog2")
        self.horizontalLayout.addWidget(self.dialog2)
        self.control = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.control.setObjectName("control")
        self.horizontalLayout.addWidget(self.control)
        self.start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 281, 91, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.current = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.current.setObjectName("current")
        self.verticalLayout.addWidget(self.current)
        self.lcdcurrent = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdcurrent.setObjectName("lcdcurrent")
        self.verticalLayout.addWidget(self.lcdcurrent)
        self.volt = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.volt.setObjectName("volt")
        self.verticalLayout.addWidget(self.volt)
        self.lcdvolt = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdvolt.setObjectName("lcdvolt")
        self.verticalLayout.addWidget(self.lcdvolt)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(550, 420, 75, 23))
        self.exit.setObjectName("exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dialog1.setText(_translate("MainWindow", "Stitch & OD"))
        self.dialog2.setText(_translate("MainWindow", "Stereo Vision"))
        self.control.setText(_translate("MainWindow", "Control"))
        self.start.setText(_translate("MainWindow", "Open Webcam"))
        self.current.setText(_translate("MainWindow", "Current"))
        self.volt.setText(_translate("MainWindow", "Voltage"))
        self.exit.setText(_translate("MainWindow", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
